# site name
prefixName: ä¸€è‘‰  #ã•ãã‚‰è˜ã
aliasName: ã®
siteName: ç§‹ã€‚
blogName: ä¸€å¶çŸ¥ç§‹ğŸƒ
author: Hesperusï½œVenus

# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /images/avatar.jpeg
url: https://www.hehuadong.cn
description: æ˜”é£ä¸èµ·ï¼Œå”¯æœ‰åŠªåŠ›ç”Ÿå­˜ã€‚Le vent se lÃ¨ve ï¼Œil faut tenter de vivreã€‚
pjax: 1
# 1å¼€å¯
mathjax: 0

# åŠ¨æ€å®šä¹‰title
title_change:
  normal: (ã¤ã‚§âŠ‚)å’¦!åˆå¥½äº†!
  leave: æ­»é¬¼å»å“ªé‡Œäº†ï¼

notice: hexo-Sakuraä¸»é¢˜å·²ç»å¼€æºï¼Œç›®å‰æ­£åœ¨å¼€å‘ä¸­...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  æŠ€æœ¯: { path: /tec, fa: fa-code-fork faa-vertical,
    submenus: { 
      æŠ€æœ¯ Â· ç¼–ç¨‹: { path: /tec/code, fa: fa-code },
      æŠ€æœ¯ Â· å·¥å…·: { path: /tec/tools, fa: fa-cog }, 
      æŠ€æœ¯ Â· æ‚è°ˆ: { path: /tec/other, fa: fa-twitch }, 
      åšå®¢ Â· Hexo: { path: /tec/hexo, fa: fa-book }, 
    },
  }
  éšç¬”: { path: /essay, fa: fa-pencil faa-shake,
    submenus: { 
      éšç¬” Â· æ—¥å¸¸: { path: /essay/daily, fa: fa-sun-o },
      éšç¬” Â· åŠ¨æ¼«: { path: /essay/anime, fa: fa-film fa-vertical }, 
      éšç¬” Â· æ¸¸æˆ: { path: /essay/game, fa: fa-gamepad }, 
      éšç¬” Â· æ‚è°ˆ: { path: /essay/other, fa: fa-gift }, 
    },
  }
  å½’æ¡£: { path: /archives, fa: fa-archive faa-shake, 
    submenus: { 
      ç”µå½± ğŸ¬: { path: /movie, fa: fa fa-video-camera }, 
      ç•ªç»„ ğŸ±: { path: /bangumi, fa: fa-film faa-vertical }, 
      æ¸¸æˆ ğŸ®: { path: /game, fa: fa fa-gamepad },
      æ­Œå• ğŸµ: { path: /music, fa: fa-headphones },
    } 
  }
  ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
  # èµèµ: { path: /donate/, fa: fa-heart faa-pulse }
  å…³äº: { path: /, fa: fa-leaf faa-wrench , 
    submenus: { 
      æˆ‘ï¼Ÿ: {path: /about/, fa: fa-meetup}, 
      ä¸»é¢˜: {path: /theme-sakura/, fa: iconfont icon-sakura },
      Lab: {path: /lab/, fa: fa-cogs },
    } 
  }

# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg_cover: 
  url: /img/cover/home/  # assets@githubä¸‹è·¯å¾„ä½ç½®
  img_num: 10  # githubä»“åº“coverå›¾ç‰‡æ•°é‡
  imgs: 
    tec: { url: https://view.amogu.cn/images/2020/08/26/20200531205547.jpg, title: æŠ€æœ¯,
      menus: { 
        code: { url: https://view.amogu.cn/images/2020/08/26/H6d670440b3db43c9b5bf0faa923a79ccp.jpg, title: æŠ€æœ¯ Â· ç¼–ç¨‹ },
        tools: { url: https://view.amogu.cn/images/2020/08/26/H0181c1c54e564d7c97cc6b68c1bcf54cS.jpg, title: æŠ€æœ¯ Â· å·¥å…· },
        other: { url: https://view.amogu.cn/images/2020/08/26/Hf742f29e16b64d3c822f0b7de5926bdeF.jpg, title: æŠ€æœ¯ Â· æ‚è°ˆ },
      }
    }
    essay: { url: https://view.amogu.cn/images/2020/08/26/H2060a5cfab6f4af694be683540dcf65eK.jpg, title: éšç¬”,
      menus: {
        daily: { url: https://view.amogu.cn/images/2020/08/26/Haf91908167c54b0aa5ee25f130d5119ai.jpg, title: éšç¬” Â· æ—¥å¸¸ },
        anime: { url: https://view.amogu.cn/images/2020/08/26/20200601124847.jpg, title: éšç¬” Â· åŠ¨æ¼« },
        game: { url: https://view.amogu.cn/images/2020/08/26/20200601124116.jpg, title: éšç¬” Â· æ¸¸æˆ },
        other: { url: https://view.amogu.cn/images/2020/08/26/20200601163919.jpg, title: éšç¬” Â· æ‚è°ˆ }
      }
    }

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-undertint æŸ”å’Œ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: filter-undertint

# ä¸»é subtitle
subtitle:
  enable: true
  # æ‰“å­—æ•ˆæœ
  effect: true
  # å¾ªç’°æˆ–è€…åªæ‰“å­—ä¸€æ¬¡
  loop: false
  # sourceèª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨æå¤©apiçš„éš¨æ©ŸèªéŒ„ï¼ˆç°¡é«”ï¼‰ https://api.btstu.cn/
  # source: 2  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰ https://hitokoto.cn/
  # source: 3  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰ http://yijuzhan.com/
  # source: 4  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰ https://www.jinrishici.com/
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: 4
  # (å¦‚æœæœ‰è‹±æ–‡é€—è™Ÿ' , 'ï¼Œè«‹ä½¿ç”¨è½‰ç¾©å­—ç¬¦ &#44;)
  # å¦‚æœé—œé–‰æ‰“å­—æ•ˆæœï¼Œsubtitleåªæœƒé¡¯ç¤ºsubçš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - ä»Šæ—¥äº‹&#44;ä»Šæ—¥ç•¢
    - Never put off till tomorrow what you can do today

# æ‰“å­—æ•ˆæœ
activate_power_mode:
  enable: true
  colorful: true # å†’å…‰ç‰¹æ•ˆ
  shake: true # æŠ–å‹•ç‰¹æ•ˆ

# é¼ æ¨™é»æ“Šæ•ˆæœ
# é¿å…å¡é “ï¼Œå»ºè­°åªé–‹å•Ÿä¸€å€‹
# é»æ“Šç…™ç«ç‰¹æ•ˆ
fireworks:
  enable: true

# é»æ“Šå‡ºç¾æ„›å¿ƒ
click_heart:
  enable: false

# é»æ“Šå‡ºç¾æ–‡å­—ï¼Œæ–‡å­—å¯è‡ªè¡Œä¿®æ”¹
click_show_text:
  enable: true
  text:
    - ã‚ˆã†ã“ã!!! (âŒ’â–½âŒ’) 
    - è¨ç“¦è¿ªå¡ï¼Œå’”å˜£å’” (âœªÏ‰âœª)
    - BiuBiuBiu ~~
  fontSize: 15px

# èƒŒæ™¯ç‰¹æ•ˆ
# é¿å…å¡é “ï¼Œå»ºè­°åªé–‹å•Ÿä¸€å€‹
# canvas_ribbon ç¦æ­¢å½©å¸¶èƒŒæ™¯
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: true
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true
  mobile: false # false æ‰‹æ©Ÿç«¯ä¸é¡¯ç¤º true æ‰‹æ©Ÿç«¯é¡¯ç¤º

# å‹•æ…‹å½©å¸¶
canvas_ribbon_piao:
  enable: true
  mobile: false # false æ‰‹æ©Ÿç«¯ä¸é¡¯ç¤º true æ‰‹æ©Ÿç«¯é¡¯ç¤º

 # æµæ˜ŸèƒŒæ™¯ç‰¹æ•ˆ
bg_meteor:
  enable: true

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: æœ¬ç«™ hexo ä¸»é¢˜, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: /img/startdash/bilibili.jpg}
  - {url: /, title: huadongçš„ä¸‡äº‹å±‹, desc: æŠ€æœ¯æœåŠ¡, img: /img/startdash/wangshiwu.jpg}

# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PCç«¯é…ç½®
social:
  github: {url: https://github.com/HesperusVenus, img: /img/social/github.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  juejin: {url: https://juejin.im/user/5c358598e51d4551e533d23d, img: /img/social/juejin.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=363967384, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/hua-dong-17-78, img: /img/social/zhihu.png}
  # email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  tencent: {url: /#, qrcode: /img/custom/tencent.png, img: /img/social/qq.png}
  wechat: {url: /#, qrcode: /img/custom/wechat.png, img: /img/social/wechat.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: http://github.com/HesperusVenus, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1210633716&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  # paypal: https://www.paypal.me/hojuncn
  # alipay: /img/custom/donate/AliPayQR.jpg
  # wechat: /img/custom/donate/WeChanQR.jpg
  # wechatSQ: /img/custom/donate/WeChanSQ.jpg
  alipay:
  wechat: 
  wechatSQ: 

#video
bg_video:
  enable: true
  url:  https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/video/bg_video/
    # - ../movies/æœ‰ä¸€ç§å¤å¤©å«å®«å´éªçš„å¤å¤©.mp4
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: 
    - æœ‰ä¸€ç§å¤å¤©å«å®«å´éªçš„å¤å¤©
    - æœ‰ä¸€ç§çˆ±æƒ…å«å¿˜æœºæ— ç¾¡
    - æœ‰ä¸€ç§æ„Ÿæƒ…å«å…„å¼Ÿæƒ…æ·±
    - æ— è®ºä½ åœ¨ä¸–ç•Œä¸Šçš„ä»€ä¹ˆåœ°æ–¹ï¼Œæˆ‘éƒ½ä¸€å®šä¼šå†å»è§ä½ 
    - å¥½æƒ³çˆ±è¿™ä¸ªä¸–ç•Œ

#live2d çœ‹æ¿å¨˜
live2d:
  enable: true  # æ˜¯å¦å¼€å¯
  model: umaru  # çœ‹æ¿å¨˜æ¨¡å‹ã€‚ nero<å°¼æ´›> || umaru<å¹²ç‰©å¦¹å°åŸ‹> || Violet<è–‡å°”è‰ç‰¹> || platelet<è¡€å°æ¿>
  mode: fixed  # æ¨¡å¼ã€‚ static || fixed || draggable
  position: left # ä½ç½®
  hidden: true, # éšè—
  width: 200
  height: 300
  dialog: '3em'

# Aplayer html5éŸ³ä¹æ’­æ”¾å™¨
aplayer: 
  enable: true # å¦‚æœä½ æƒ³ä½¿ç”¨aplayerï¼Œè¯·å°†å€¼è®¾ç½®ä¸º true
  id: 2555162702  # æ­Œæ›²id / æ­Œå•id / ä¸“è¾‘id / å…³é”®å­—<ç®€å•æµ‹è¯•æ— æ•ˆæœ>
  server: netease  # éŸ³ä¹å¹³å°: netease<ç½‘æ˜“äº‘>, tencent<è…¾è®¯QQéŸ³ä¹>, kugou<é…·ç‹—>, xiami<è™¾ç±³>, baidu<ç™¾åº¦>
  type: playlist
  fixed: true  # å¸åº•æ¨¡å¼;é»˜è®¤å€¼false
  autoplay: false # è‡ªåŠ¨æ’­æ”¾
  loop: all #éŸ³é¢‘å¾ªç¯æ’­æ”¾, å¯é€‰å€¼: 'all', 'one', 'none'
  order: random # éŸ³é¢‘å¾ªç¯é¡ºåº, å¯é€‰å€¼: 'list', 'random'
  preload: auto # é¢„åŠ è½½ï¼Œå¯é€‰å€¼: 'none', 'metadata', 'auto'
  volume: 0.7 # é»˜è®¤éŸ³é‡
  mutex: true # äº’æ–¥ï¼Œé˜»æ­¢å¤šä¸ªæ’­æ”¾å™¨åŒæ—¶æ’­æ”¾ï¼Œå½“å‰æ’­æ”¾å™¨æ’­æ”¾æ—¶æš‚åœå…¶ä»–æ’­æ”¾å™¨

# Dplayer html5å¼¹å¹•è§†é¢‘æ’­æ”¾å™¨
dplayer:
  enable: true     # å¦‚æœä½ æƒ³ä½¿ç”¨dplayerï¼Œè¯·å°†å€¼è®¾ç½®ä¸º true
  theme: '#1bd1a5' # ä¸»é¢˜é¢œè‰²
  autoplay: false  # è‡ªåŠ¨æ’­æ”¾
  loop: false      # è§†é¢‘å¾ªç¯æ’­æ”¾
  lang: 'zh-cn'    # å¯é€‰å€¼: 'en', 'zh-cn', 'zh-tw'
  screenshot: true # å¼€å¯æˆªå›¾ï¼Œå¦‚æœå¼€å¯ï¼Œè§†é¢‘å’Œè§†é¢‘å°é¢éœ€è¦å…è®¸è·¨åŸŸ
  hotkey: false     # å¼€å¯çƒ­é”®ï¼Œæ”¯æŒå¿«è¿›ã€å¿«é€€ã€éŸ³é‡æ§åˆ¶ã€æ’­æ”¾æš‚åœ
  airplay: true    # åœ¨ Safari ä¸­å¼€å¯ AirPlay
  preload: 'auto'  # è§†é¢‘é¢„åŠ è½½, å¯é€‰å€¼: 'none', 'metadata', 'auto'
  volume: 0.7      # éŸ³é‡, è¯·æ³¨æ„æ’­æ”¾å™¨ä¼šè®°å¿†ç”¨æˆ·è®¾ç½®ï¼Œç”¨æˆ·æ‰‹åŠ¨è®¾ç½®éŸ³é‡åé»˜è®¤éŸ³é‡å³å¤±æ•ˆ
  playbackSpeed: [0.5, 0.75, 1, 1.25, 1.5, 2] #å¯é€‰çš„æ’­æ”¾é€Ÿç‡
  mutex: true      # äº’æ–¥, é˜»æ­¢å¤šä¸ªæ’­æ”¾å™¨åŒæ—¶æ’­æ”¾ï¼Œå½“å‰æ’­æ”¾å™¨æ’­æ”¾æ—¶æš‚åœå…¶ä»–æ’­æ”¾å™¨
  logo:  '../images/favicon.ico'          # å·¦ä¸Šè§’logo
  playlist:  
    Movie: 
      - { video:{ title: 'æ€æˆ®éƒ½å¸‚O' , pic: 'pic.jpg' , type: 'customHls', species: 'ç”µå½±ğŸ¬', class: 'movie'}, subtitle_url: 'xxx' }

    ç•ªå‰§ğŸ±:
      - 

# Dplayer subtitle  è§†é¢‘æ’­æ”¾å™¨å­—å¹•      
dplayer_sub:
  enable: false
  type: 'webvtt'    # å­—å¹•ç±»å‹ï¼Œå¯é€‰å€¼: 'webvtt', 'ass'ï¼Œç›®å‰åªæ”¯æŒ webvtt
  fontSize: '12px'  # å­—å¹•å­—å·
  bottom: '60%'     # å­—å¹•è·ç¦»æ’­æ”¾å™¨åº•éƒ¨çš„è·ç¦»ï¼Œå–å€¼å½¢å¦‚: '10px' '10%'
  color: '#fff'     # å­—å¹•é¢œè‰²

# Valine
valine: true
v_appId: bczUNaxHjOUz63D94Yw5dsar-gzGzoHsz
v_appKey: 8HAfLX9oICaQRFRS3Q9iHj0M

#CDN
CDN:
  # main
  main: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets

  # background effect
  canvas_ribbon: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/js/third-party/canvas_ribbon.min.js
  canvas_ribbon_piao: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/js/third-party/canvas_ribbon_piao.min.js
  typed: https://cdn.jsdelivr.net/npm/typed.js@latest/lib/typed.min.js

  # æ‰“å­—ç‰¹æ•ˆ
  activate_power_mode: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/js/third-party/activate_power_mode.min.js

  # é¼ æ¨™é»æ“Šç‰¹æ•ˆ
  fireworks: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/js/third-party/fireworks.min.js
  click_heart: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/js/third-party/click_heart.min.js
  click_show_text: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/js/third-party/click_show_text.min.js

  # æµæ˜ŸèƒŒæ™¯ç‰¹æ•ˆ
  bg_meteor: https://cdn.jsdelivr.net/gh/HesperusVenus/assets@master/assets/js/third-party/bg_meteor.min.js

  #live2d
  live2d: https://cdn.jsdelivr.net/gh/HesperusVenus/live2d@master/live2d.js
  live2d_piocss: https://cdn.jsdelivr.net/gh/HesperusVenus/live2d@1.01/pio.css
  live2d_piojs: https://cdn.jsdelivr.net/gh/HesperusVenus/live2d@1.01/pio.js
  live2d_model: https://cdn.jsdelivr.net/gh/HesperusVenus/live2d@latest/models

  #aplayer
  aplayer: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.js
  aplayer_css: https://cdn.jsdelivr.net/npm/aplayer@latest/dist/APlayer.min.css
  meting: https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js

  #dplayer
  dplayer: https://cdn.jsdelivr.net/gh/DIYgod/DPlayer@latest/dist/DPlayer.min.js
  hls: https://cdn.jsdelivr.net/npm/hls.js@latest/dist/hls.min.js

  #video
  video: https://cdn.jsdelivr.net/npm/video.js@7.10.1/dist/video.min.js
  video_css: https://cdn.jsdelivr.net/npm/video.js@7.10.1/dist/video-js.css
  video_contrib_hls: https://cdn.jsdelivr.net/npm/videojs-contrib-hls@latest/dist/videojs-contrib-hls.min.js